export { default as Account } from './Account';
export { default as Cart } from './Cart';
export { default as Collections } from './Collections';
export { default as Home } from './Home';
export { default as NewArrivals } from './NewArrivals';
export { default as Shop } from './Shop';
export { default as Wishlist } from './Wishlist';
export { default as Search } from './Search'
export { default as ProductDetails } from './ProductDetails'
export { default as Checkout } from './Checkout'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as MyOrders } from './MyOrders'